# Generated by Django 4.2.28 on 2026-02-09 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNugget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, unique=True)),
                ('stoic_quote', models.TextField()),
                ('author', models.CharField(default='Marcus Aurelius', max_length=100)),
                ('daily_challenge', models.CharField(max_length=255)),
            ],
        ),
    ]
